### ISSUE TITLE
setInterstitialCallback() doesn't work

### ISSUE THREAD

**Issue by AGulev** [enhance-co/defold-connector#8]
Callback do not call after interstitial ads was finished

**Comment by kacper-weiland** [comment]
Hello @AGulev ,

I'm sorry for the inconvenience!

`setInterstitialCallback()` is a function which we deprecated in all of our connector libraries quite a long ago. We keep it in the project only for backward compatibility and I presume it won't work with most of the SDKs that Enhance supports currently.
We might, however, look into this issue and bring back this function to life in the future. Please provide us more detailed description of the problem and an instruction on how to reproduce it.

Does it happen all the time or only for particular SDKs?
What are the parameters of your testing device? (e.g. OS version)
How do you use it in your code? (A snippet would be helpful!)

Thanks!

**Comment by AGulev** [comment]
Hello @kacperwd,
I pause the game when start showing an ads.  Then, when ads is done and I receive callback setInterstitialCallback() - I unpause the game.
This flow works fine, but after one of updates I recived a lot of bad reviews because game didn't unpause after ads.

I reproduce this problem on Android 6.0 (Xiaomi redmi note 4), but my users reproduce the same on different devices.
I am using: unity ads, charboost, admob, vungle, adcolony, apploving.

**Comment by lpmitchell** [comment]
Hi @AGulev,

Apologies for the issues that you've found with this method. The method is undocumented (and now deprecated) because we're unable to guarantee it's reliability, for example if a certain ad network fails to dispatch a 'complete' event then it won't fire.

We are currently working on some updates which will introduce some new event callbacks, however our advice will still be to not rely on the events alone for game state management. Our best advice is as follows:

Continue to use the callback, but when you call showInterstitialAd you should push a 'Tap to resume' onto your paused app. If the callback fires successfully then the screen will be auto-dismissed and the user experience will be unchanged, but if there is a case where it fails the user can simply tap to continue playing.
